version: '3'

services:
  frontend:
    build: ./learngram-fe
    volumes: 
      - ./learngram-fe:/usr/src/app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
  backend:
    build: ./learngram-assignment
    volumes: 
      - ./learngram-assignment:/usr/src/app
    ports:
      - "5000:5000"
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local